spring:
  application:
    name: invoiceiq-backend
  profiles:
    active: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

jobrunr:
  dashboard:
    enabled: false
